#!/bin/bash -x -e

PARENT_DIR=$(dirname "$0")
cd "$PARENT_DIR"/../..
ABS_PATH="$(pwd)"
cd - >/dev/null
echo $ABS_PATH

CFLAGS="-Wall -nostdinc -mkernel -D_KERNEL -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -I$ABS_PATH/include -I$ABS_PATH/../spl/include -I/System/Library/Frameworks/Kernel.framework/PrivateHeaders -I/System/Library/Frameworks/Kernel.framework/Headers -DZFS_META_VERSION=\"0.6.0\" -DZFS_META_RELEASE=\"rc12\" -DHAVE_SPL=1 -DNAMEDSTREAMS=1"

# Two ## means the source file still needs to be ported.
#gcc $CFLAGS -o zvol.o -c zvol.c
#gcc $CFLAGS -o zfs_acl.o -c zfs_acl.c
#gcc $CFLAGS -o zfs_vnops.o -c zfs_vnops.c
#exit

gcc $CFLAGS -o arc.o -c arc.c
gcc $CFLAGS -o bplist.o -c bplist.c
gcc $CFLAGS -o bpobj.o -c bpobj.c
gcc $CFLAGS -o bptree.o -c bptree.c
gcc $CFLAGS -o dbuf.o -c dbuf.c
gcc $CFLAGS -o ddt.o -c ddt.c
gcc $CFLAGS -o ddt_zap.o -c ddt_zap.c
gcc $CFLAGS -o dmu.o -c dmu.c
gcc $CFLAGS -o dmu_diff.o -c dmu_diff.c
gcc $CFLAGS -o dmu_object.o -c dmu_object.c
gcc $CFLAGS -o dmu_objset.o -c dmu_objset.c
gcc $CFLAGS -o dmu_send.o -c dmu_send.c
gcc $CFLAGS -o dmu_traverse.o -c dmu_traverse.c
gcc $CFLAGS -o dmu_tx.o -c dmu_tx.c
gcc $CFLAGS -o dmu_zfetch.o -c dmu_zfetch.c
gcc $CFLAGS -o dnode.o -c dnode.c
gcc $CFLAGS -o dnode_sync.o -c dnode_sync.c
gcc $CFLAGS -o dsl_dataset.o -c dsl_dataset.c
gcc $CFLAGS -o dsl_deadlist.o -c dsl_deadlist.c
gcc $CFLAGS -o dsl_deleg.o -c dsl_deleg.c
gcc $CFLAGS -o dsl_dir.o -c dsl_dir.c
gcc $CFLAGS -o dsl_pool.o -c dsl_pool.c
gcc $CFLAGS -o dsl_prop.o -c dsl_prop.c
gcc $CFLAGS -o dsl_scan.o -c dsl_scan.c
gcc $CFLAGS -o dsl_synctask.o -c dsl_synctask.c
gcc $CFLAGS -o fm.o -c fm.c
gcc $CFLAGS -o gzip.o -c gzip.c
gcc $CFLAGS -o lzjb.o -c lzjb.c
gcc $CFLAGS -o metaslab.o -c metaslab.c
gcc $CFLAGS -o refcount.o -c refcount.c
gcc $CFLAGS -o rrwlock.o -c rrwlock.c
gcc $CFLAGS -o sa.o -c sa.c
gcc $CFLAGS -o sha256.o -c sha256.c
gcc $CFLAGS -o spa.o -c spa.c
gcc $CFLAGS -o spa_boot.o -c spa_boot.c
gcc $CFLAGS -o spa_config.o -c spa_config.c
gcc $CFLAGS -o spa_errlog.o -c spa_errlog.c
gcc $CFLAGS -o spa_history.o -c spa_history.c
gcc $CFLAGS -o spa_misc.o -c spa_misc.c
gcc $CFLAGS -o space_map.o -c space_map.c
gcc $CFLAGS -o txg.o -c txg.c
gcc $CFLAGS -o uberblock.o -c uberblock.c
gcc $CFLAGS -o unique.o -c unique.c
gcc $CFLAGS -o vdev.o -c vdev.c
gcc $CFLAGS -o vdev_cache.o -c vdev_cache.c
gcc $CFLAGS -o vdev_disk.o -c vdev_disk.c
gcc $CFLAGS -o vdev_file.o -c vdev_file.c
gcc $CFLAGS -o vdev_label.o -c vdev_label.c
gcc $CFLAGS -o vdev_mirror.o -c vdev_mirror.c
gcc $CFLAGS -o vdev_missing.o -c vdev_missing.c
gcc $CFLAGS -o vdev_queue.o -c vdev_queue.c
gcc $CFLAGS -o vdev_raidz.o -c vdev_raidz.c
gcc $CFLAGS -o vdev_root.o -c vdev_root.c
gcc $CFLAGS -o zap.o -c zap.c
gcc $CFLAGS -o zap_leaf.o -c zap_leaf.c
gcc $CFLAGS -o zap_micro.o -c zap_micro.c
gcc $CFLAGS -o zfeature.o -c zfeature.c
gcc $CFLAGS -o zfeature_common.o -c zfeature_common.c
gcc $CFLAGS -o zfs_acl.o -c zfs_acl.c
gcc $CFLAGS -o zfs_byteswap.o -c zfs_byteswap.c
##gcc $CFLAGS -o zfs_ctldir.o -c zfs_ctldir.c
gcc $CFLAGS -o zfs_debug.o -c zfs_debug.c
gcc $CFLAGS -o zfs_dir.o -c zfs_dir.c
gcc $CFLAGS -o zfs_fm.o -c zfs_fm.c
gcc $CFLAGS -o zfs_fuid.o -c zfs_fuid.c
gcc $CFLAGS -o zfs_ioctl.o -c zfs_ioctl.c
gcc $CFLAGS -o zfs_log.o -c zfs_log.c
gcc $CFLAGS -o zfs_onexit.o -c zfs_onexit.c
gcc $CFLAGS -o zfs_osx.o -c zfs_osx.c
##gcc $CFLAGS -o zfs_replay.o -c zfs_replay.c
gcc $CFLAGS -o zfs_rlock.o -c zfs_rlock.c
##gcc $CFLAGS -o zfs_sa.o -c zfs_sa.c
gcc $CFLAGS -o zfs_vfsops.o -c zfs_vfsops.c
gcc $CFLAGS -o zfs_vnops.o -c zfs_vnops.c
gcc $CFLAGS -o zfs_znode.o -c zfs_znode.c
gcc $CFLAGS -o zil.o -c zil.c
gcc $CFLAGS -o zio.o -c zio.c
gcc $CFLAGS -o zio_checksum.o -c zio_checksum.c
gcc $CFLAGS -o zio_compress.o -c zio_compress.c
gcc $CFLAGS -o zio_inject.o -c zio_inject.c
gcc $CFLAGS -o zle.o -c zle.c
##gcc $CFLAGS -o zpl_ctldir.o -c zpl_ctldir.c
##gcc $CFLAGS -o zpl_export.o -c zpl_export.c
##gcc $CFLAGS -o zpl_file.o -c zpl_file.c
##gcc $CFLAGS -o zpl_inode.o -c zpl_inode.c
##gcc $CFLAGS -o zpl_super.o -c zpl_super.c
##gcc $CFLAGS -o zpl_xattr.o -c zpl_xattr.c
gcc $CFLAGS -o zrlock.o -c zrlock.c
gcc $CFLAGS -o zvol.o -c zvol.c

## avl
gcc $CFLAGS -o avl.o -c ../avl/avl.c

## nvpair
gcc $CFLAGS -o fnvpair.o -c ../nvpair/fnvpair.c
gcc $CFLAGS -o nvpair.o -c ../nvpair/nvpair.c
gcc $CFLAGS -o nvpair_alloc_fixed.o -c ../nvpair/nvpair_alloc_fixed.c
gcc $CFLAGS -o nvpair_alloc_spl.o -c ../nvpair/nvpair_alloc_spl.c

## unicode
gcc $CFLAGS -o u8_textprep.o -c ../unicode/u8_textprep.c
gcc $CFLAGS -o uconv.o -c ../unicode/uconv.c

## zcommon
gcc $CFLAGS -o zfs_comutil.o -c ../zcommon/zfs_comutil.c
gcc $CFLAGS -o zfs_deleg.o -c ../zcommon/zfs_deleg.c
gcc $CFLAGS -o zfs_fletcher.o -c ../zcommon/zfs_fletcher.c
gcc $CFLAGS -o zfs_namecheck.o -c ../zcommon/zfs_namecheck.c
gcc $CFLAGS -o zfs_prop.o -c ../zcommon/zfs_prop.c
##gcc $CFLAGS -o zfs_uio.o -c ../zcommon/zfs_uio.c
gcc $CFLAGS -o zpool_prop.o -c ../zcommon/zpool_prop.c
gcc $CFLAGS -o zprop_common.o -c ../zcommon/zprop_common.c

mkdir -p zfs.kext/Contents/Resources/English.lproj zfs.kext/Contents/MacOS
cp -f Info.plist zfs.kext/Contents/
cp -f InfoPlist.strings zfs.kext/Contents/Resources/English.lproj/

gcc -o zfs.kext/Contents/MacOS/zfs *.o -Xlinker -kext -nostdlib -lkmodc++ -lkmod -lcc_kext || echo "Linking failed"

#kextlibs -r /Users/lundman/src/zfs/osx.zfs/x/spl/module/spl/ -undef-symbols -xml zfs.kext/ && echo "Build successful"
kextlibs -undef-symbols -xml zfs.kext/ && echo "Build successful"
