/*
 * Generated by dtrace(1M).
 */

#ifndef	_ZFS_DTRACE_GEN_H
#define	_ZFS_DTRACE_GEN_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define ZFS_STABILITY "___dtrace_stability$zfs$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define ZFS_TYPEDEFS "___dtrace_typedefs$zfs$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	ZFS_ZFS_DBGMSG(arg0) \
do { \
	__asm__ volatile(".reference " ZFS_TYPEDEFS);		  \
	__dtrace_probe$zfs$zfs__dbgmsg$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " ZFS_STABILITY); \
} while (0)
#define	ZFS_ZFS_DBGMSG_ENABLED() \
	({ int _r = __dtrace_isenabled$zfs$zfs__dbgmsg$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$zfs$zfs__dbgmsg$v1$63686172202a(const char *);
extern int __dtrace_isenabled$zfs$zfs__dbgmsg$v1(void);

#else

#define	ZFS_ZFS_DBGMSG(arg0) \
do { \
	} while (0)
#define	ZFS_ZFS_DBGMSG_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _ZFS_DTRACE_GEN_H */
